import json
from semantic import semantic_similarity
from getHeaderUsingLLM import get_header_LLM
from getAtcCode import get_final_codes
from getRoutes import get_adminstration_routes_array
from getMahSection import get_MAH_Details_LLM

def get_section_codes():
    with open('smpc/sectionCodes.json', 'r') as json_file:
      data = json.load(json_file)
    return data["sections"]




# {
#   "content": [
    # {
    #   "section_title": "",
    #   "section_string": ""
    # },
#     {
#       "section_title": "",
#       "section_string": ""
#     }
#   ]
# }





def splitAndGetCode(titles,content):
    code_sections = get_section_codes()
    result = []
    indexes = []
    last_index = 0
    for i, current_section in enumerate(titles):
        index = 0
        highest_similarity = 0.0
        for j , line in enumerate(content):
            if last_index > j:
                continue
            similarity_ratio = semantic_similarity(current_section, line , lang="en")
            print(current_section, line , similarity_ratio , highest_similarity)
            if similarity_ratio > highest_similarity or similarity_ratio >= 0.95:
                if similarity_ratio > highest_similarity:
                 last_index = index

                highest_similarity = similarity_ratio
                index = j
            if similarity_ratio >= 0.95:
                break
        indexes.append(index)
    print(indexes)
    for i , index in enumerate(indexes):
        
        if i == len(indexes) - 1:
            result.append({"title": titles[i], "content": content[index:], "code": ""  , "display":"", "semantic_similarity": 0.0})	
        else:
            result.append({"title": titles[i], "content": content[index:indexes[i+1]] , "code": "","display":"", "semantic_similarity": 0.0})
        
    for i , res in enumerate(result):
        section_title = res["title"]
        found = False
        for db_section in code_sections:
            if section_title.lower() == db_section["Display"].lower():
                result[i]["code"] = db_section["Code"]
                found = True
                break

        if found:
            continue
        highest_similarity = 0
        section_code = ""
        display = ""
        for db_section in code_sections:
             simlarity = semantic_similarity(section_title , db_section["Display"])
             if simlarity > highest_similarity: 
                    highest_similarity = simlarity
                    section_code = db_section["Code"]
                    display = db_section["Display"]
        if highest_similarity >= 0.8:
         result[i]["code"] = section_code
         result[i]["display"] = display
         result[i]["semantic_similarity"] = highest_similarity
        else:
            result[i]["code"] = "Not Found"
            result[i]["semantic_similarity"] = 0.0
    return result




def get_smpc(titles,content):
    sections = []
    result = {}
    try:
        sections = splitAndGetCode(titles,content)
        result.update({"sections": sections})
    except Exception as e:  
        print(e , "error could not split sections and get codes , please make sure the order of the sections titles is correct")
        return {"error": "error could not split sections and get codes , please make sure the order of the sections titles is correct"}
    


    try:
        header = []
        for i , section in enumerate(sections):
            header.extend(section["content"])
            if i == 3:
                break
        header = get_header_LLM(header , smpc=True)
        result.update({"header": header})
    except(Exception) as e:
        print (e , {"error": "failed to generate header section details"})
        result.update({"header": None})

    # get atc code 
    try:
        active = header.get("active_substances")
        if len(active) > 0:
          print("multiple active substances found , complex PIL or wrongly detected substances")
        for i , section in enumerate(sections):
            if section["code"] == "34067-9":
                indication_usage_section = section["content"]
                break
        atc_code = get_final_codes(indication_usage_section, active[0])
        result.update({"atc_code": atc_code})
    except(Exception) as e:
        result.update({"atc_code": None})
        print (e , {"error": "failed to get ATC code , due to missing proper section in the leaflet,wrong active substance generated by the LLM or due to complex PIL with multiple active substances"})


    # get routes of administration
    try:
        for i , section in enumerate(sections):
            if section["code"] == "34068-7":
                indication_usage_section = section["content"]
                break
        routes = get_adminstration_routes_array(indication_usage_section)
        result.update({"routes": routes})
    except(Exception) as e:
        result.update({"routes": None})
        print (e , {"error": "failed to get routes"})

    try:
        MAH_section= []
        MAH_section.extend(sections[-1]["content"] , sections[-2]["content"] , sections[-3]["content"])
        MAH_details = get_MAH_Details_LLM(MAH_section)
        result.update({"MAH_details": MAH_details})
    except(Exception) as e:
        result.update({"MAH_details": None})
        print (e , {"error": "failed to generate MAH details"})
    return result
    # result = {"sections": sections , "header": "" , "atc_code": "" , "routes":"", "MAH_details": ""}
    
